// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN_O1ShKuWd6mKs1y0y-qod8qaG0dGzw0',
    appId: '1:1038216231838:web:650d85b8cfb5ab0e52748f',
    messagingSenderId: '1038216231838',
    projectId: 'floixemapp-b8281',
    authDomain: 'lacasadelsueloradianteapp.com',
    storageBucket: 'floixemapp-b8281.firebasestorage.app',
    measurementId: 'G-0RBVSGF2B7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrDVTRstNEHzU8dWp0PiL9YZ2bX_zzKWw',
    appId: '1:1038216231838:android:f918f8a083d836ab52748f',
    messagingSenderId: '1038216231838',
    projectId: 'floixemapp-b8281',
    storageBucket: 'floixemapp-b8281.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE4IF3ddToGidSl6uTJec8juoha0iBsxg',
    appId: '1:1038216231838:ios:cf8879d4dc3d674652748f',
    messagingSenderId: '1038216231838',
    projectId: 'floixemapp-b8281',
    storageBucket: 'floixemapp-b8281.firebasestorage.app',
    iosClientId: '1038216231838-5il28dcni0k0qsguedn0ekmp5om3uc3f.apps.googleusercontent.com',
    iosBundleId: 'com.example.floixemapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE4IF3ddToGidSl6uTJec8juoha0iBsxg',
    appId: '1:1038216231838:ios:5deafdbe20334c8a52748f',
    messagingSenderId: '1038216231838',
    projectId: 'floixemapp-b8281',
    storageBucket: 'floixemapp-b8281.firebasestorage.app',
    iosClientId: '1038216231838-q8jp87a1qfighhr16d3m31u7lbmmvi7v.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN_O1ShKuWd6mKs1y0y-qod8qaG0dGzw0',
    appId: '1:1038216231838:web:23ae45c81413b13d52748f',
    messagingSenderId: '1038216231838',
    projectId: 'floixemapp-b8281',
    authDomain: 'floixemapp-b8281.firebaseapp.com',
    storageBucket: 'floixemapp-b8281.firebasestorage.app',
    measurementId: 'G-WQRRH5X1XW',
  );
}
